name = "farmable-backend"
main = "functions/index.ts"
compatibility_date = "2025-02-01"

[[d1_databases]]
binding = "DB"
database_name = "farmable-database"
database_id = "6cd713c9-04f3-4edc-9569-33f7f85de808"